FROM rust:latest as builder
RUN rustup target add x86_64-unknown-linux-musl
COPY . .
RUN cargo install --target=x86_64-unknown-linux-musl --path .

FROM debian:bullseye-slim
COPY --from=builder /usr/local/cargo/bin/togetherness /usr/local/bin/togetherness
CMD ["togetherness"]
