FROM rust:latest as builder
RUN rustup target add x86_64-unknown-linux-musl
WORKDIR /app
# download and build dependencies into cache
COPY Cargo.* ./
RUN \
    mkdir src && \
    echo 'fn main() {}' > src/main.rs && \
    cargo build --release --target=x86_64-unknown-linux-musl && \
    rm -rf src
# build our actual code
COPY src src
RUN \
    touch src/main.rs && \
    cargo build --release --target=x86_64-unknown-linux-musl

FROM alpine:latest
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/togetherness /usr/local/bin/togetherness
CMD ["togetherness"]
